task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-14-0
  install_script:
    - pkg install -y git gmake
    - curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 sh
  script:
    - export PATH="$HOME/.ghcup/bin:$PATH"
    - cabal test --test-show-details=direct

task:
  name: OpenBSD
  compute_engine_instance:
    image_project: pg-ci-images
    # See https://github.com/anarazel/pg-vm-images/blob/main/packer/openbsd.pkrvars.hcl
    image: family/pg-ci-openbsd-vanilla
    platform: openbsd
  install_script: pkg_add ghc cabal-install git
  script:
    - export CABAL_DIR=/tmp/.cabal
    - cabal update
    - cabal test --test-show-details=direct

task:
  name: NetBSD
  compute_engine_instance:
    image_project: pg-ci-images
    # See https://github.com/anarazel/pg-vm-images/blob/main/packer/netbsd.pkrvars.hcl
    image: family/pg-ci-netbsd-vanilla
    platform: netbsd
  install_script:
    # Folders should be updated in line with
    # http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/
    - export PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All/;http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/9.0_2023Q1/All/"
    - echo $PKG_PATH
    - pkg_add ghc cabal-install git
  script:
    - export CABAL_DIR=/tmp/.cabal
    - cabal update
    - cabal test --test-show-details=direct
