name: arm
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  # We use github.com/haskell self-hosted runners for ARM testing.
  # If they become unavailable in future, put ['armv7', 'aarch64']
  # back to emulated.yml.
  arm:
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      fail-fast: true
      matrix:
        arch: [arm64v8]
    steps:
      - uses: docker://hasufell/arm64v8-ubuntu-haskell:focal
        name: Cleanup
        with:
          args: "find . -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +"

      - name: Checkout code
        uses: actions/checkout@v7

      - uses: docker://hasufell/arm64v8-ubuntu-haskell:focal
        name: Run build (arm64v8 linux)
        with:
          args: sh -c "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1 sh && cabal update && cabal test -w ~/.ghcup/bin/ghc"
