name: centos
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
    - name: install deps
      run: |
        yum install -y gcc gmp gmp-devel make ncurses ncurses-compat-libs ncurses-devel xz perl libstdc++-static
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh
    - uses: actions/checkout@v2
    - name: Test
      run: |
        source ~/.ghcup/env
        cabal update
        cabal test -f-simdutf
